* ChangeLog for emacs-util
** [2021-06-08 Tue 14:32]
   - Added ChangeLog and License.
   - ~util/hidden-buffers~ now has regexp optional.
   - Bug fix for ~util/try-copy-help-buffer-link~.
   - ~util/rgrep-default-search` now ignores `node_modules~ directory for JS files
     and ~env~ dir for python files.
   - ~util/org-collect-headings~ now has only one predicate. It used to have two.
   - Fixed a bug in ~util/org-multi-collect-headings~ where buffer timestamps weren't
     being checked correctly.
   - Fixed consequent bugs in ~util/org-insert-link-to-heading~.
   - Added a ~citation` option to `util/org-insert-link-to-heading~ and consequent
     text collection code.
   - Added a helper routine ~util/org-get-text-links~ to get links from org text body.
   - Added a function ~util/run-python-file-from-str~ but it isn't useful yet.
   - Version bump to 0.2.0.

** [2021-06-08 Tue 14:32]
   - Separated some functionality of ~util/org-insert-link-to-heading~ into
     subroutines.
   - Added suggestions from ~references` in `util/org-insert-link-to-heading~
   - Added macros ~util/with-check-mode`, `util/with-org-mode~ etc.
   - Added time stamp functions ~util/insert-or-update-time-stamp-at-point~,
     ~util/insert-or-update-today~
   - Added org utility functions ~util/org-apply-to-buffer-headings~,
     ~util/org-apply-to-subtree-headings`, `util/org-heading-and-body-bounds~,
     ~util/org-get-subtree-with-body-for-heading-matching-re~
   - Modified ~util/org-multi-collect-headings~ to optionally return only headings
     for ~bufname~. Slight modifications to few other org functions.
   - ~util/org-collect-duplicate-headings~ is now much faster.
   - Added ~util/org-helm-*~ helm actions.
   - Added ffip like grep commands ~util/ffip-search-paths`, `util/ffip-search~,
     ~util/ffip-grep-default`, `util/ffip-grep-git-files~ and associated functions.
   - Version bump to ~0.3.0~.

** [2021-09-13 Mon 10:03]
   - Fixed ~util/file-link-re~
   - Changed ~util/org-execute-org-heading-max-match-search~ to
     ~util/org-execute-customid-or-max-heading-match-search~.
   - Fixed ~util/org-get-tree-prop` for not getting `doc-root` when at `doc-root~
   - Added ~util/org-insert-citation-to-heading-from-cache`, `util/org-collect-duplicate-customids~,
     ~util/org-helm-show-duplicate-customids`, `util/org-helm-headings~ and subroutine for it
   - Version bump to ~0.3.1~
   - Added ~util/org-execute-search-funcall` and separated `util/org-execute-search-find-pdf-file~.
   - Separated ~util/org-execute-search-heading-length-subr~ and streamlined
     ~util/org-execute-customid-or-max-heading-match-search~
   - Added ~util/vars-matching-re~
   - Version bump to ~0.3.2~.

** [2021-09-21 Tue 14:02]
   - Fixed a bug that inserted incorrect links when doing so in current buffer for
     ~util/org-insert-link-to-heading~
   - Version bump will be automatic from now.

** [2021-09-24 Fri 12:26]
   - Fixed a bug in ~util/org-execute-customid-or-max-heading-match-search~ where
     in case custom-id being searched is not found
   - Added ~util/org-delete-file-under-point` and `util/org-move-file-under-point~

** [2021-09-28 Tue 16:50]
   - Fixed some compatibility issues with older ~emacs-version==25.x.x~
   - Removed ~sphinx-doc~ as dependency.

** [2021-10-06 Wed 16:06]
   - Added ~util/org-helm-copy-link-to-entry` and `util/copy-link-to-heading~ and
     helper functions with some variables.
   - Also added ~util/org-remove-links~

** [2021-10-11 Mon 10:13]
   - Fixed a couple of regexps
   - Changed ChangeLog.md to ChangeLog.org

** [2021-10-12 Tue 17:01]
   - Separted helm functions to ~util-helm-org.el~.
   - Added some pure spec declarations.

** [2021-10-17 Sun 21:09]
   - Separated org functions to ~util-org.el~.

** [2021-11-05 Fri 09:06]
   - Added ~util/org-execute-search-other-window~ and
     ~util/org-execute-search-find-pdf-file~
   - ~util/org-execute-search-prefix-arg-behaviour~ is now
     ~util/org-execute-search-prefix-arg-behaviour-alist~
   - Added ~util/org-filter-from-headings-cache~
   - Added ~util/check-mode~ as still haven't figured out how to instrument the
     macro correctly.
   - Removed the tern function

** [2021-11-13 Sat 10:11]
   - Fixed a couple of incorrect helm-org symbols
   - Finished implementation for ~util/org-move-file-under-point~
   - Fixed incorrect predicate call in ~util/org-filter-from-headings-cache~
   - Added sort by installation date in ~util/package-top-level-packages~

** [2021-11-23 Tue 11:20]
   - Fixed a small bug with ~util/org-rename-file-under-point~ which caused
     incorrect shortened names.

** [2021-12-02 Thu 16:56]
   - New subroutine ~util/org-execute-search-goto-point~ to goto point after
     executing search
   - Fixed a bug in full match in ~util/org-execute-customid-or-max-heading-match-search~
     Cleaner implementation also.

** [2022-01-26 Wed 16:15]
   - Added ~(debug t)~ instead of more verbose debug declarations. Still don't
     understand it.
   - Fixed arguments of ~util/package-top-level-packages~.
   - Added optional check if grepping in > 50 files for ~util/ffip-grep-git-files~.
   - Removed obsolete ~cdass~
   - New functions ~util/org-get-headings-at-level~,
     ~util/org-link-get-target-for-internal~,
     ~util/org-find-references~, ~util/org-copy-link-under-point~,
     ~util/org-copy-links-to-multiple-headings~
   - Fixed ~util/helm-org-show-outline~ and some other ~util/helm-org~ functions
   - Fixed docs.

** [2022-01-27 Thu 12:52]
   - Split the files into spearate packages based on use. Cask doesn't work for
     these. Will have to find an alternative way to compile, perhaps with a
     preloading script with cask.

** [2022-02-03 Thu 18:10]
   - Added function ~util/update-time-stamp-in-project-files~
   - Fixed pruning bug in ~util/ffip-search~

** [2022-02-23 Wed 19:38]
   - Added function ~util/url-buffer-string~ in ~util-core.el~. And somehow the
     bug for ~util/ffip-search~ was still there. I'm not sure what's going on
     with the find command. Perhaps different switches.
   - In file ~util-org.el~
     - Rearranged symbols so that variables are on top.
     - The ~predicate~ works differently now for ~util/org-collected-headings~.
       The headings are collected without any filter and any predicate is
       applied after collection. Earlier ~util/org-collect-headings-subr~ would
       collect headings based on a predicate.
       Dependencies to those functions also changed.
     - ~util/org-collect-headings-subr~ now takes no arguments.
     - ~util/org-default-heading-filter-p~ now checks for custom-id and heading length.
     - New convience functions ~util/org-get-beginning-of-link~ and
       ~util/org-get-bracket-link-bounds~
     - New command ~util/org-convert-link-to-description~
   - In file ~util-helm-org.el~
     - ~util/helm-org-headings~ now takes an optional ~headings~ argument to
       display the headings.

** [2022-03-03 Thu 09:14]
   - New function ~util/org-get-bracket-link-description~ and updated
     ~util/org-rename-file-under-point~.
   - New function ~util/org-rename-file-remove-opening-braces~ and modification
     to ~util/org-shorten-link-description-to-file-name~
   - Some more changes to ~util/ffip-search~. It's still buggy though.

** [2022-05-17 Tue 04:11]
   - In ~util-core.el~
     - Some fixes to ~util/update-time-stamp-in-project-files~ and ~util/package-desc~
     - ~util/rgrep-default-search~ can now also search in ~gz~ files if visited file
       is ~gz~
   - In ~util-org.el~, new variables ~util/org-text-link-re~ and ~util/org-text-http-link-re~
     - ~util/org-get-tree-prop~ also takes ~top-level~ as an optional argument

** [2022-06-03 Fri 15:37]
   - Changed ~clip-func~ in ~util/org-insert-citation-to-heading~ to
     ~util/org-citation-function~
